'use client';

import Sidebar from '@/components/dashboard/Sidebar';
import YieldCurveChart from '@/components/analytics/YieldCurveChart';
import MarketHeatmap from '@/components/analytics/MarketHeatmap';
import PredictiveForecast from '@/components/analytics/PredictiveForecast';
import SentimentAnalysis from '@/components/analytics/SentimentAnalysis';
import TokenizationTracker from '@/components/dashboard/TokenizationTracker';
import { Menu, Search, Bell } from 'lucide-react';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';

export default function AnalyticsPage() {
    const router = useRouter();
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        // Auth check
        const user = localStorage.getItem('user');
        if (!user) router.push('/login');
        setLoading(false);
    }, [router]);

    if (loading) return null;

    return (
        <div className="min-h-screen bg-[#050b14] text-slate-200 font-sans selection:bg-amber-500/30">
            <Sidebar />

            <div className="lg:pl-64 flex flex-col min-h-screen relative z-10">

                {/* Header */}
                <header className="px-6 py-4 flex items-center justify-between sticky top-0 bg-[#050b14]/80 backdrop-blur-xl z-30 border-b border-white/5">
                    <div className="lg:hidden">
                        <Menu className="w-6 h-6 text-white" />
                    </div>

                    <div className="font-bold text-lg text-white">Market Analytics</div>

                    <div className="flex items-center gap-4">
                        <div className="relative hidden md:block">
                            <input
                                type="text"
                                placeholder="Search reports..."
                                className="bg-slate-900/50 border border-slate-800 rounded-lg pl-9 pr-4 py-1.5 text-sm focus:border-blue-500 focus:outline-none w-64 text-white"
                            />
                            <Search className="w-4 h-4 text-slate-500 absolute left-3 top-2" />
                        </div>
                        <button className="p-2 text-slate-400 hover:text-white transition relative">
                            <Bell className="w-5 h-5" />
                            <span className="absolute top-2 right-2 w-2 h-2 bg-red-500 rounded-full border border-[#050b14]" />
                        </button>
                    </div>
                </header>

                <main className="p-6 grid grid-cols-1 xl:grid-cols-2 gap-6">

                    {/* Row 1: Macro View */}
                    <div className="space-y-6">
                        <YieldCurveChart />
                        <PredictiveForecast />
                    </div>

                    {/* Row 2: Sector & Sentiment */}
                    <div className="space-y-6">
                        <MarketHeatmap />
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <SentimentAnalysis />
                            <div className="space-y-6">
                                <div className="glass-panel p-6 rounded-2xl flex flex-col justify-center h-[200px] border border-blue-500/20 bg-blue-500/5 relative overflow-hidden">
                                    <h3 className="text-lg font-bold text-white mb-2 relative z-10">AI Report</h3>
                                    <p className="text-sm text-blue-200 mb-4 relative z-10">
                                        Download the comprehensive weekly bond market outlook generated by our models.
                                    </p>
                                    <button className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold rounded-lg transition width-fit relative z-10">
                                        Download PDF
                                    </button>
                                    <div className="absolute -right-10 -bottom-10 w-40 h-40 bg-blue-500/20 rounded-full blur-2xl z-0" />
                                </div>
                                <div className="h-[126px]">
                                    <TokenizationTracker />
                                </div>
                            </div>
                        </div>
                    </div>

                </main>
            </div>
        </div>
    );
}
